// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type User struct {
	ID       int32          `json:"id"`
	Email    sql.NullString `json:"email"`
	Username sql.NullString `json:"username"`
	Password sql.NullString `json:"password"`
}

type UserDetail struct {
	ID       int32          `json:"id"`
	UserID   sql.NullInt32  `json:"user_id"`
	Fullname sql.NullString `json:"fullname"`
	Phone    sql.NullString `json:"phone"`
	Gender   sql.NullString `json:"gender"`
}
